package pojo;
// Generated Dec 16, 2011 9:36:07 AM by Hibernate Tools 3.2.1.GA



/**
 * Emailnhanthongbao generated by hbm2java
 */
public class Emailnhanthongbao  implements java.io.Serializable {


     private Integer idEmailNhanThongBao;
     private String email;

    public Emailnhanthongbao() {
    }

    public Emailnhanthongbao(String email) {
       this.email = email;
    }
   
    public Integer getIdEmailNhanThongBao() {
        return this.idEmailNhanThongBao;
    }
    
    public void setIdEmailNhanThongBao(Integer idEmailNhanThongBao) {
        this.idEmailNhanThongBao = idEmailNhanThongBao;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


