package pojo;
// Generated Dec 16, 2011 9:36:07 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Hinhthucmuahang generated by hbm2java
 */
public class Hinhthucmuahang  implements java.io.Serializable {


     private Integer idHinhThucMuaHang;
     private String tenHinhThucMuaHang;
     private Set<Dondathang> dondathangs = new HashSet<Dondathang>(0);

    public Hinhthucmuahang() {
    }

    public Hinhthucmuahang(String tenHinhThucMuaHang, Set<Dondathang> dondathangs) {
       this.tenHinhThucMuaHang = tenHinhThucMuaHang;
       this.dondathangs = dondathangs;
    }
   
    public Integer getIdHinhThucMuaHang() {
        return this.idHinhThucMuaHang;
    }
    
    public void setIdHinhThucMuaHang(Integer idHinhThucMuaHang) {
        this.idHinhThucMuaHang = idHinhThucMuaHang;
    }
    public String getTenHinhThucMuaHang() {
        return this.tenHinhThucMuaHang;
    }
    
    public void setTenHinhThucMuaHang(String tenHinhThucMuaHang) {
        this.tenHinhThucMuaHang = tenHinhThucMuaHang;
    }
    public Set<Dondathang> getDondathangs() {
        return this.dondathangs;
    }
    
    public void setDondathangs(Set<Dondathang> dondathangs) {
        this.dondathangs = dondathangs;
    }




}


