package pojo;
// Generated Dec 16, 2011 9:36:07 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  implements java.io.Serializable {


     private Integer idKhachHang;
     private String tenKhachHang;
     private String diaChi;
     private String email;
     private String dienThoai;
     private String matKhau;
     private Float taiKhoan;
     private String hinhAnh;
     private Integer deleted;
     private Set<Dondathang> dondathangs = new HashSet<Dondathang>(0);

    public Khachhang() {
    }

    public Khachhang(String tenKhachHang, String diaChi, String email, String dienThoai, String matKhau, Float taiKhoan, String hinhAnh, Integer deleted, Set<Dondathang> dondathangs) {
       this.tenKhachHang = tenKhachHang;
       this.diaChi = diaChi;
       this.email = email;
       this.dienThoai = dienThoai;
       this.matKhau = matKhau;
       this.taiKhoan = taiKhoan;
       this.hinhAnh = hinhAnh;
       this.deleted = deleted;
       this.dondathangs = dondathangs;
    }
   
    public Integer getIdKhachHang() {
        return this.idKhachHang;
    }
    
    public void setIdKhachHang(Integer idKhachHang) {
        this.idKhachHang = idKhachHang;
    }
    public String getTenKhachHang() {
        return this.tenKhachHang;
    }
    
    public void setTenKhachHang(String tenKhachHang) {
        this.tenKhachHang = tenKhachHang;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDienThoai() {
        return this.dienThoai;
    }
    
    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }
    public String getMatKhau() {
        return this.matKhau;
    }
    
    public void setMatKhau(String matKhau) {
        this.matKhau = matKhau;
    }
    public Float getTaiKhoan() {
        return this.taiKhoan;
    }
    
    public void setTaiKhoan(Float taiKhoan) {
        this.taiKhoan = taiKhoan;
    }
    public String getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(String hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Integer getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
    public Set<Dondathang> getDondathangs() {
        return this.dondathangs;
    }
    
    public void setDondathangs(Set<Dondathang> dondathangs) {
        this.dondathangs = dondathangs;
    }




}


