package pojo;
// Generated Dec 16, 2011 9:36:07 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Nhacungcap generated by hbm2java
 */
public class Nhacungcap  implements java.io.Serializable {


     private Integer idNhaCungCap;
     private String tenNhaCungCap;
     private String diaChi;
     private String banDo;
     private Set<Phieumuahang> phieumuahangs = new HashSet<Phieumuahang>(0);

    public Nhacungcap() {
    }

    public Nhacungcap(String tenNhaCungCap, String diaChi, String banDo, Set<Phieumuahang> phieumuahangs) {
       this.tenNhaCungCap = tenNhaCungCap;
       this.diaChi = diaChi;
       this.banDo = banDo;
       this.phieumuahangs = phieumuahangs;
    }
   
    public Integer getIdNhaCungCap() {
        return this.idNhaCungCap;
    }
    
    public void setIdNhaCungCap(Integer idNhaCungCap) {
        this.idNhaCungCap = idNhaCungCap;
    }
    public String getTenNhaCungCap() {
        return this.tenNhaCungCap;
    }
    
    public void setTenNhaCungCap(String tenNhaCungCap) {
        this.tenNhaCungCap = tenNhaCungCap;
    }
    public String getDiaChi() {
        return this.diaChi;
    }
    
    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }
    public String getBanDo() {
        return this.banDo;
    }
    
    public void setBanDo(String banDo) {
        this.banDo = banDo;
    }
    public Set<Phieumuahang> getPhieumuahangs() {
        return this.phieumuahangs;
    }
    
    public void setPhieumuahangs(Set<Phieumuahang> phieumuahangs) {
        this.phieumuahangs = phieumuahangs;
    }




}


