package pojo;
// Generated Dec 16, 2011 9:36:07 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Phieumuahang generated by hbm2java
 */
public class Phieumuahang  implements java.io.Serializable {


     private Integer idPhieuMuaHang;
     private Nhacungcap nhacungcap;
     private Danhmuc danhmuc;
     private String tenPhieuHang;
     private String moTa;
     private String chiTiet;
     private Date thoiGianBatDau;
     private Date thoiGianKetThuc;
     private Float giaGoc;
     private Integer tietKiem;
     private String dieuKien;
     private String hinhAnh;
     private Integer soLuong;
     private Boolean tinhTrangPhieu;
     private Integer soLuongDaBan;
     private Integer deleted;
     private long thoiGianConLai;
     private Set<Dondathang> dondathangs = new HashSet<Dondathang>(0);

    public Phieumuahang() {
    }

    public Phieumuahang(Nhacungcap nhacungcap, Danhmuc danhmuc, String tenPhieuHang, String moTa, String chiTiet, Date thoiGianBatDau, Date thoiGianKetThuc, Float giaGoc, Integer tietKiem, String dieuKien, String hinhAnh, Integer soLuong, Boolean tinhTrangPhieu, Integer soLuongDaBan, Integer deleted, Set<Dondathang> dondathangs) {
       this.nhacungcap = nhacungcap;
       this.danhmuc = danhmuc;
       this.tenPhieuHang = tenPhieuHang;
       this.moTa = moTa;
       this.chiTiet = chiTiet;
       this.thoiGianBatDau = thoiGianBatDau;
       this.thoiGianKetThuc = thoiGianKetThuc;
       this.giaGoc = giaGoc;
       this.tietKiem = tietKiem;
       this.dieuKien = dieuKien;
       this.hinhAnh = hinhAnh;
       this.soLuong = soLuong;
       this.tinhTrangPhieu = tinhTrangPhieu;
       this.soLuongDaBan = soLuongDaBan;
       this.deleted = deleted;
       this.dondathangs = dondathangs;
    }
   
    public Integer getIdPhieuMuaHang() {
        return this.idPhieuMuaHang;
    }
    
    public void setIdPhieuMuaHang(Integer idPhieuMuaHang) {
        this.idPhieuMuaHang = idPhieuMuaHang;
    }
    public Nhacungcap getNhacungcap() {
        return this.nhacungcap;
    }
    
    public void setNhacungcap(Nhacungcap nhacungcap) {
        this.nhacungcap = nhacungcap;
    }
    public Danhmuc getDanhmuc() {
        return this.danhmuc;
    }
    
    public void setDanhmuc(Danhmuc danhmuc) {
        this.danhmuc = danhmuc;
    }
    public String getTenPhieuHang() {
        return this.tenPhieuHang;
    }
    
    public void setTenPhieuHang(String tenPhieuHang) {
        this.tenPhieuHang = tenPhieuHang;
    }
    public String getMoTa() {
        return this.moTa;
    }
    
    public void setMoTa(String moTa) {
        this.moTa = moTa;
    }
    public String getChiTiet() {
        return this.chiTiet;
    }
    
    public void setChiTiet(String chiTiet) {
        this.chiTiet = chiTiet;
    }
    public Date getThoiGianBatDau() {
        return this.thoiGianBatDau;
    }
    
    public void setThoiGianBatDau(Date thoiGianBatDau) {
        this.thoiGianBatDau = thoiGianBatDau;
    }
    public Date getThoiGianKetThuc() {
        return this.thoiGianKetThuc;
    }
    
    public void setThoiGianKetThuc(Date thoiGianKetThuc) {
        this.thoiGianKetThuc = thoiGianKetThuc;
    }
    public Float getGiaGoc() {
        return this.giaGoc;
    }
    
    public void setGiaGoc(Float giaGoc) {
        this.giaGoc = giaGoc;
    }
    public Integer getTietKiem() {
        return this.tietKiem;
    }
    
    public void setTietKiem(Integer tietKiem) {
        this.tietKiem = tietKiem;
    }
    public String getDieuKien() {
        return this.dieuKien;
    }
    
    public void setDieuKien(String dieuKien) {
        this.dieuKien = dieuKien;
    }
    public String getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(String hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }
    public Boolean getTinhTrangPhieu() {
        return this.tinhTrangPhieu;
    }
    
    public void setTinhTrangPhieu(Boolean tinhTrangPhieu) {
        this.tinhTrangPhieu = tinhTrangPhieu;
    }
    public Integer getSoLuongDaBan() {
        return this.soLuongDaBan;
    }
    
    public void setSoLuongDaBan(Integer soLuongDaBan) {
        this.soLuongDaBan = soLuongDaBan;
    }
    public Integer getDeleted() {
        return this.deleted;
    }
    
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }
    public Set<Dondathang> getDondathangs() {
        return this.dondathangs;
    }
    
    public void setDondathangs(Set<Dondathang> dondathangs) {
        this.dondathangs = dondathangs;
    }

    /**
     * @return the thoiGianConLai
     */
    public long getThoiGianConLai() {
        return thoiGianConLai;
    }

    /**
     * @param thoiGianConLai the thoiGianConLai to set
     */
    public void setThoiGianConLai(long thoiGianConLai) {
        this.thoiGianConLai = thoiGianConLai;
    }




}


