package pojo;
// Generated Dec 16, 2011 9:36:07 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tinhtrangdondathang generated by hbm2java
 */
public class Tinhtrangdondathang  implements java.io.Serializable {


     private Integer idTinhTrang;
     private String tenTinhTrang;
     private Set<Dondathang> dondathangs = new HashSet<Dondathang>(0);

    public Tinhtrangdondathang() {
    }

    public Tinhtrangdondathang(String tenTinhTrang, Set<Dondathang> dondathangs) {
       this.tenTinhTrang = tenTinhTrang;
       this.dondathangs = dondathangs;
    }
   
    public Integer getIdTinhTrang() {
        return this.idTinhTrang;
    }
    
    public void setIdTinhTrang(Integer idTinhTrang) {
        this.idTinhTrang = idTinhTrang;
    }
    public String getTenTinhTrang() {
        return this.tenTinhTrang;
    }
    
    public void setTenTinhTrang(String tenTinhTrang) {
        this.tenTinhTrang = tenTinhTrang;
    }
    public Set<Dondathang> getDondathangs() {
        return this.dondathangs;
    }
    
    public void setDondathangs(Set<Dondathang> dondathangs) {
        this.dondathangs = dondathangs;
    }




}


